import type { Metadata } from "next";
import "./globals.css";

// app/layout.tsx
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <html>
      <head>
        <title>CMS Client</title>
      </head>
      <body>{children}</body>
    </html>
  );
};

export default Layout;
